name: ValantisSTATS
version: '${project.version}'
main: org.wally.valantisstats.ValantisSTATS
api-version: '1.20'
load: STARTUP

commands:
  valstats:
    description: Set a persistent data on the player